### ISSUE TITLE
[warning]Unexpected input 'time', valid inputs are ['']

### ISSUE THREAD

**Issue by anuzis** [jakejarvis/wait-action#2]
Using the suggested syntax from the README this action works great (as expected), but GitHub Actions logs always reports a warning:

##[warning]Unexpected input 'time', valid inputs are ['']

Looking around online, it appears this may be a new behavior from Github Actions while it's in beta.

ref: https://github.com/samuelmeuli/lint-action/issues/53
Excerpt from 17 hours ago as of this writing: "I've just gotten the same thing pop up, I was testing this last week and wasn't hitting it, all of a sudden it has appeared."

Not sure what the fix is yet, but it seems likely Github Actions beta will announce a way to specify expected input values, probably resolving this.

**Comment by bcmedeiros** [comment]
Same problem here:
<img width="545" alt="image" src="https://user-images.githubusercontent.com/251695/86990536-62e83e80-c1cf-11ea-821b-0a669f2adf28.png">

**Comment by whatnick** [comment]
This action needs an `action.yaml` and [input metadata](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#inputs)

**Comment by tylerpayne-kinoo** [comment]
Still getting the issue

```Warning: Unexpected input(s) 'time', valid inputs are ['entryPoint', 'args']```
